[train] Fix issues with new HTTP inference codepath and add weight sync tests (#1016)
# What does this PR do?

Fixes some issues with the new HTTP inference codepath (see RFC
https://github.com/NovaSky-AI/SkyRL/issues/845) and adds basic weight
sync tests


1. CLI Parsing: The GSM8K example fails with
`_SKYRL_USE_NEW_INFERENCE=1` with a `AttributeError`:

```bash
(pid=3677738, ip=10.0.153.235, actor_id=66beaa83e5a5ee29a61a169213010000, repr=<skyrl_train.inference_servers.vllm_server_actor.VLLMServerActor object at 0x7b0ea4afa720>)
[36m(skyrl_entrypoint pid=3675949)[0m   File "/home/ray/anaconda3/lib/python3.12/concurrent/futures/_base.py", line 449, in result
[36m(skyrl_entrypoint pid=3675949)[0m     return self.__get_result()
[36m(skyrl_entrypoint pid=3675949)[0m            ^^^^^^^^^^^^^^^^^^^
[36m(skyrl_entrypoint pid=3675949)[0m   File "/home/ray/anaconda3/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
[36m(skyrl_entrypoint pid=3675949)[0m     raise self._exception
[36m(skyrl_entrypoint pid=3675949)[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(skyrl_entrypoint pid=3675949)[0m   File "/tmp/ray/session_2026-01-28_12-40-25_893362_5766/runtime_resources/working_dir_files/_ray_pkg_825ce54be2c8b337/skyrl_train/inference_servers/vllm_server_actor.py", line 231, in start
[36m(skyrl_entrypoint pid=3675949)[0m     await self._wait_until_healthy()
[36m(skyrl_entrypoint pid=3675949)[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(skyrl_entrypoint pid=3675949)[0m   File "/tmp/ray/session_2026-01-28_12-40-25_893362_5766/runtime_resources/working_dir_files/_ray_pkg_825ce54be2c8b337/skyrl_train/inference_servers/vllm_server_actor.py", line 246, in _wait_until_healthy
[36m(skyrl_entrypoint pid=3675949)[0m     raise exc
[36m(skyrl_entrypoint pid=3675949)[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(skyrl_entrypoint pid=3675949)[0m   File "/tmp/ray/session_2026-01-28_12-40-25_893362_5766/runtime_resources/working_dir_files/_ray_pkg_825ce54be2c8b337/skyrl_train/inference_servers/vllm_server_actor.py", line 266, in _run_server
[36m(skyrl_entrypoint pid=3675949)[0m     app = build_app(self._cli_args)
[36m(skyrl_entrypoint pid=3675949)[0m           ^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(skyrl_entrypoint pid=3675949)[0m   File "/home/ray/.cache/uv/builds-v0/.tmpCvhl19/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 961, in build_app
[36m(skyrl_entrypoint pid=3675949)[0m     if args.disable_fastapi_docs:
[36m(skyrl_entrypoint pid=3675949)[0m        ^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(skyrl_entrypoint pid=3675949)[0m AttributeError: 'Namespace' object has no attribute 'disable_fastapi_docs'
```

The core issue is that we construct an ad-hoc namespace object while
vLLM expects an object containing all supported fields - this includes
fields in vLLM's `FrontendArgs` and `AsyncEngineArgs`. This PR uses the
same argument parsing logic as in vLLM :
https://github.com/vllm-project/vllm/blob/e346e2d056a66bb84287e4fea049bde9a37bd72b/vllm/entrypoints/openai/cli_args.py#L276-L313

and then overrides with SkyRL's configuration. 

2. Session re-use in `RemoteInferenceClient`: In some tests in GPU CI,
we create multiple event loops in the same test. `RemoteInferenceClient`
creates an `aiohttp.ClientSession` object which is valid for the
original event loop only. The fix is to check if the event loop has
changed and re-create the session

3. vLLM server placement for colocated training: For colocated training,
the new HTTP inference codepath diverged from the existing
Ray-actor-based codepath
([here](https://github.com/NovaSky-AI/SkyRL/blob/d1e1b297717195f9b54cb36f68c79d6aa406baed/skyrl-train/skyrl_train/inference_engines/ray_wrapped_inference_engine.py#L81))
in placement - the vllm servers were created with the default resource
of 1 GPU per vLLM rank, which will not work for colocated training.

4. Unit tests: Added unit testing for the new codepath for weight
syncing for the colocated and the non-colocated case. Tests pass after
the above fixes.

Misc: Also moved registration of `VLLMServerActor` with GCS to be
global, one time

---------

Signed-off-by: SumanthRH <sumanthrh99@gmail.com>
Co-authored-by: gemini-code-assist[bot] <176961590+gemini-code-assist[bot]@users.noreply.github.com>