Revert "[skyrl-train] Updated RoPE Configuration for HF Models transformers) w. backward-compatible support for vLLM (#690)" (#695)
#690 breaks main:

```python
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2025-11-10_23-41-08_808638_5823/runtime_resources/working_dir_files/_ray_pkg_70495ea0ae6ec02c/skyrl_train/workers/fsdp/fsdp_worker.py", line 66, in init_model
    wrapped_model = HFModelWrapper(
                    ^^^^^^^^^^^^^^^
  File "/tmp/ray/session_2025-11-10_23-41-08_808638_5823/runtime_resources/working_dir_files/_ray_pkg_70495ea0ae6ec02c/skyrl_train/model_wrapper.py", line 117, in __init__
    self.model = model_class.from_pretrained(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/.cache/uv/builds-v0/.tmpxGZQ4v/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 604, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/.cache/uv/builds-v0/.tmpxGZQ4v/lib/python3.12/site-packages/transformers/modeling_utils.py", line 277, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ray/.cache/uv/builds-v0/.tmpxGZQ4v/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4971, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Qwen2ForCausalLM.__init__() got an unexpected keyword argument 'rope_parameters'
```